import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/NavigationMenu";
import { Toaster } from "@/components/ui/toaster";

import { Providers } from "./providers";
import { SiteConfig } from "@/src/site-config";
import PlausibleProvider from "next-plausible";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App Sticker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" className="h-full" suppressHydrationWarning>
        <head>
          <PlausibleProvider domain={SiteConfig.domain} />
        </head>
        <body className={inter.className}>
          <Providers>
            <main>
              <div className="flex justify-center items-center p-4">
                <NavigationMenu />
              </div>
              {children}
            </main>
            <Toaster />
          </Providers>
        </body>
      </html>
    </>
  );
}
